services:
  postgres:
    image: pgvector/pgvector:0.8.6-pg16-trixie
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${DB_USER}        
      POSTGRES_PASSWORD: ${DB_PASSWORD} 
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      # Persists the database data on your local machine
      - postgres_data:/var/lib/postgresql/data
      # Maps your initialization script into the container
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

volumes:
  postgres_data: